#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "master" = "$branch" ]; then
    echo "Running pre-push actions for the master branch..."
    VERSION=$(cat VERSION)                                                                                                          
    export VERSION 
    docker compose build
    docker compose push
fi
