"""auth_functionality

Revision ID: b3a1faa2d044
Revises: df06393c4d14
Create Date: 2026-03-12 09:20:43.403375

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3a1faa2d044'
down_revision: Union[str, None] = 'df06393c4d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), server_default='', nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('family_members') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_family_members_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('menus') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_menus_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('products') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_products_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('recipes') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_recipes_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes') as batch_op:
        batch_op.drop_constraint('fk_recipes_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint('fk_products_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    with op.batch_alter_table('menus') as batch_op:
        batch_op.drop_constraint('fk_menus_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    with op.batch_alter_table('family_members') as batch_op:
        batch_op.drop_constraint('fk_family_members_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
