"""initial schema

Revision ID: df06393c4d14
Revises: 
Create Date: 2026-03-10 22:06:59.560473

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df06393c4d14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('portion_multiplier', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('dietary_restrictions', sa.String(), server_default='', nullable=False),
    sa.Column('comment', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipe_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('units',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_group', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), server_default='', nullable=False),
    sa.Column('supplier', sa.String(), server_default='', nullable=False),
    sa.Column('recipe_unit', sa.String(), nullable=False),
    sa.Column('purchase_unit', sa.String(), nullable=False),
    sa.Column('price_per_purchase_unit', sa.Float(), server_default='0', nullable=False),
    sa.Column('weight_per_piece_g', sa.Float(), nullable=True),
    sa.Column('conversion_factor', sa.Float(), server_default='1.0', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['purchase_unit'], ['units.name'], ),
    sa.ForeignKeyConstraint(['recipe_unit'], ['units.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('dietary_tags', sa.String(), server_default='[]', nullable=False),
    sa.Column('servings', sa.Integer(), server_default='1', nullable=False),
    sa.Column('weight', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['recipe_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooking_steps',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'step_order')
    )
    op.create_table('menu_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('servings_override', sa.Float(), nullable=True),
    sa.CheckConstraint('(recipe_id IS NOT NULL AND product_id IS NULL) OR (recipe_id IS NULL AND product_id IS NOT NULL)', name='check_slot_xor'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit'], ['units.name'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    op.drop_table('menu_slots')
    op.drop_table('cooking_steps')
    op.drop_table('recipes')
    op.drop_table('products')
    op.drop_table('units')
    op.drop_table('recipe_categories')
    op.drop_table('product_categories')
    op.drop_table('menus')
    op.drop_table('family_members')
    # ### end Alembic commands ###
