from typing import Any, Protocol


class EntityExporter(Protocol):
    """Serializes domain entities to bytes in a specific format."""

    def export_bytes(self, entities: list[Any]) -> bytes: ...
    def example_bytes(self) -> bytes: ...
    def content_type(self) -> str: ...
    def file_extension(self) -> str: ...
