name: deploy

on:
  push:
    branches: [ "master" ]

jobs:

  update-containers:

    runs-on: self-hosted

    steps:
    - name: Update version
      run: source ~/menutor/.config/.env ; curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.raw+json" -H "X-GitHub-Api-Version: 2026-03-10" -o ~/menutor/VERSION "https://api.github.com/repos/zhdanovaekaterina/menutor/contents/VERSION"
    - name: Down the containers
      run: docker compose -f ~/menutor/docker-compose.yml down
    - name: Pull the containers
      run: docker compose -f ~/menutor/docker-compose.yml pull
    - name: Apply migrations
      run: docker compose -f ~/menutor/docker-compose.yml run backend alembic upgrade head
    - name: Up the containers
      run: docker compose -f ~/menutor/docker-compose.yml up -d --remove-orphans
